---
version: "3.7"
services:
  everybot:
    restart: always
    container_name: everybot
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app

  everybot-db:
    restart: always
    container_name: everybot-db
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=everybotdb
    env_file:
      - .env
    expose:
      - 27017
